added mpa-7103 - basic CRUD tests for configuration service
scalecube/scalecube-configuration-service pull request #31
Opened 2018-11-28 15:48 UTC by PavloPetrina

Automation testing for the configuration service - basic CRUD tests

2018-12-12 13:52 UTC, aharonha commented on scalecube-configuration/src/test/java/resources/features/mpa-7103-Automation-testing-for-the-configuration-servicen.feature
> +  Scenario: Fail to save (edit) the write permission for specific entity which already exist (duplicate)
```suggestion
  Scenario: Update (override - edit) the write permission for specific entity which already exist
```

2018-12-12 13:53 UTC, aharonha commented on scalecube-configuration/src/test/java/resources/features/mpa-7103-Automation-testing-for-the-configuration-servicen.feature
> +    And the user should get one of the error messages: "key: "specified" key name already exists" or "value": "specified" value name already exists"
```suggestion
        Then both new entities (keys and values) should be created and stored in the relevant "repository" of the DB
```

2018-12-12 14:03 UTC, aharonha commented on scalecube-configuration/src/test/java/resources/features/mpa-7103-Automation-testing-for-the-configuration-servicen.feature
> +    Then this new entity (key or value) shouldn't be created
```suggestion
```

2018-12-12 14:07 UTC, aharonha commented on scalecube-configuration/src/test/java/resources/features/mpa-7103-Automation-testing-for-the-configuration-servicen.feature
> +  Scenario: Fail to save a duplicate of existent instrument instance entity
should not fail

2018-12-12 14:23 UTC, aharonha requested changes
do some changes

2018-12-14 11:08 UTC, PavloPetrina commented on scalecube-configuration/src/test/java/resources/features/mpa-7103-Automation-testing-for-the-configuration-servicen.feature
> +  Scenario: Fail to save a duplicate of existent instrument instance entity
Agreed

2019-01-02 13:12 UTC, aharonha approved these changes

2019-01-02 13:12 UTC, aharonha commented on scalecube-configuration/src/test/java/resources/features/mpa-7103-Automation-testing-for-the-configuration-servicen.feature
> +    Given a user have got a valid "tokens" (API key) with assigned "admin" and "owner" roles
token

2019-01-02 13:12 UTC, aharonha commented on scalecube-configuration/src/test/java/resources/features/mpa-7103-Automation-testing-for-the-configuration-servicen.feature
> +    Given a user have got a valid "tokens" (API key) with assigned "admin" and "owner" roles
```suggestion
     Given a user have got a valid "token" (API key) with assigned "owner" role
```

2019-01-02 13:12 UTC, aharonha commented on scalecube-configuration/src/test/java/resources/features/mpa-7103-Automation-testing-for-the-configuration-servicen.feature
> +    When this user requested to save (update) the these "specific" entities (key or value) in the relevant "repositories" name "Repo1" and "Repo2" applying the "admin" and "owner" tokens
```suggestion
     When this user requested to update a "specific" value in the relevant "repositories" name "Repo1" and "Repo2" applying the "admin" and "owner" tokens
```

2019-01-02 13:12 UTC, aharonha commented on scalecube-configuration/src/test/java/resources/features/mpa-7103-Automation-testing-for-the-configuration-servicen.feature
> +    Then existent entity values shouldn't be duplicated thus new values should be set to the given keys and stored in the relevant "repositories" of the DB
`existent` -> `the existing`

2019-01-02 13:14 UTC, skolomiiets approved these changes

2019-01-02 13:17 UTC, merged