Clean up pom
scalecube/scalecube-configuration-service pull request #57
Opened 2018-12-28 13:48 UTC by dmytro-lazebnyi

2018-12-31 14:45 UTC, aharonha submitted a review, later dismissed
fix the extra tags if needed

2018-12-31 14:45 UTC, aharonha commented on scalecube-configuration/pom.xml
> +    <extratags>${env.TRAVIS_COMMIT}</extratags>
the same as https://github.com/scalecube/scalecube-organization-service/pull/58#discussion_r244578246

2019-01-08 11:16 UTC, segabriel submitted a review, later dismissed

2019-01-10 13:37 UTC, aharonha approved these changes

2019-01-10 13:39 UTC, aharonha commented on scalecube-configuration/pom.xml
> +    <extratags>${env.TRAVIS_COMMIT}</extratags>
```suggestion
    <!-- <extratags>${env.TRAVIS_COMMIT}</extratags> -->
```

2019-01-10 13:41 UTC, aharonha commented on pom.xml
> +  <version>2.0.15-SNAPSHOT</version>
```suggestion
  <version>2.0.17-SNAPSHOT</version>
```

2019-01-10 13:42 UTC, aharonha requested changes
fix version

2019-01-10 14:02 UTC, aharonha approved these changes

2019-01-10 14:04 UTC, segabriel approved these changes

2019-01-10 14:04 UTC, merged